/*  Helper class which computes the data type of a field
 *	Revision History: 
 *	
 *	Version			Author				Date				Description 
 *	1.0				Amol Chaudhari		02/02/2013			Intial Draft 
 */
 
public with sharing class FieldTypeHelper {

    //Determines the Salesforce Data Type of the Field from the provided Metadata Information 
     public static String getFieldTypeDetails(Schema.Describefieldresult pFieldResult){
     
        return null;
     }
}